# frozen_string_literal: true

source "https://rubygems.org"

gem "json"
gem "link-header-parser"
gem "log_formatter"
gem "rest-client"
gem 'time_difference'

group :development do
  # the aws-sdk is already available in the lambda environment
  gem "aws-sdk-ssm"
end
